#!/usr/bin/env bash

# ------------
# export bin
# ------------
export UOS_PATH=$HOME/data/usr/local
export PATH=$PATH:$UOS_PATH/bin:/usr/local/go/bin

# ------------
# install libs
# ------------
export INSTALL_PREFIX=$HOME/data/usr/local
export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:$INSTALL_PREFIX/lib/pkgconfig

# ----------
# toolchains
# ----------

# hi3536d
export HI3536D_GCC_PATH=$HOME/data/opt/toolchains/hisi/arm-hisiv510-linux/target/bin
export PATH=$PATH:$HI3536D_GCC_PATH


# -------
# minigui
# -------
export PATH=$PATH:$INSTALL_PREFIX/bin
export MG_CFG_PATH=$INSTALL_PREFIX

# ----
# java
# ----
export JAVA_HOME=$HOME/data/opt/jdk1.8.0_144
export JRE_HOME=$JAVA_HOME/jre
export CLASSPATH=.:$JAVA_HOME/lib:$JRE_HOME/lib:$CLASSPATH
export PATH=$PATH:$JAVA_HOME/bin:$JRE_HOME/bin

# ------------
# plantuml jar
# ------------
export PLANTUML_JAR_PATH=$HOME/data/usr/local/lib/plantuml.jar
